### ISSUE TITLE
Kubescape Scan doesn't work in Lens

### ISSUE THREAD

**Issue by yf-odyssey** [kubescape/lens-extension#8]
Dear  @amirmalka ,
   
   I tested kubescape and it perform good! So I want  to use the Lens to view several K8s cluster security report. But after I install lens-extension of kubescape，I click the Scan button and it doesn't work. It seemed that I met the similari problem as the [black screen #3](https://github.com/kubescape/lens-extension/issues/3). Because I installed Lens in Windows enviroments , so I decided to open a new issue for it.
![image](https://user-images.githubusercontent.com/33337184/198209847-910e44b8-c441-417d-8943-281b9977bd41.png)

   The relevant information is described as follows:
1. I installed the Lens in windows 10 and the Lens is downloaded from it's website(https://k8slens.dev/). Lens version is the as below. But I think its version is v6.x because when lauch it the icon show that(Lens 6).
![image](https://user-images.githubusercontent.com/33337184/198210275-176cd000-6356-4b30-8a54-fc375f6e70aa.png)
2. I installed the K8s cluster in a centos (Centos 7)virtual machine and also installed the kubescape. The kubescape works correctly in CLI, just as below.
![image](https://user-images.githubusercontent.com/33337184/198211299-ca277094-7812-42c4-8083-209a11320774.png)
3. I followed the instruction to instll kubescape extension in Lens .But it doesn't automatically scan the k8s cluster and click the scan button doesn't work also.
4. I read the "black screen #3" and also tried to uninstall the kubescape extension and deleted the files in the dir(_**C:\Users\RKHD\AppData\Roaming\Lens\extension_data_** and _**C:\Users\RKHD\AppData\Roaming\Lens\extension-store\@kubescape**_). Then I installed it again but the problem remains.  After I click the Scan button I checked the dir(C:\Users\RKHD\AppData\Roaming\Lens\extension_data\756ffa6a545a062276ff3de6d165494b811044faef8558f25d1f71baab813d8f) and find it's blank. Just as blow.
![image](https://user-images.githubusercontent.com/33337184/198212746-2d7014fc-b878-49b1-997e-21fbc40453b8.png)

Pls help me to find out the problem and thanks a lot!

**Comment by yf-odyssey** [comment]
I also uploaded the two json files in the dir(C:\Users\RKHD\AppData\Roaming\Lens\extension-store\@kubescape\lens-extension), just as blow .I hope it will help. 
![image](https://user-images.githubusercontent.com/33337184/198223154-7ca5e312-1808-4c79-850f-e95e13cecbc7.png)
[lens-extension.zip](https://github.com/kubescape/lens-extension/files/9876984/lens-extension.zip)

I also checkt the two json files and find that the scanframework label is blank. Is it related to the problem? But I have downloaded the framwork manually  just as below.
![image](https://user-images.githubusercontent.com/33337184/198223352-67bbd593-4a5e-4fcb-ad00-e480f20ca68a.png)

**Comment by amirmalka** [comment]
Dup of #10
